### ISSUE TITLE
Need the requirment.txt file

### ISSUE THREAD

**Issue by GhostDragon124** [MrGiovanni/ContinualLearning#6]
Dear author, congratulations on your work being accepted. Could you please upload the requirment.txt?

**Comment by Lilistudent** [comment]
Do you get the requirment.txt file?How to get it?Can you share with us?

**Comment by MrGiovanni** [comment]
Hello @GhostDragon124 and @Lilistudent 

Hello @mingsiliu557 

I just uploaded [requirements.txt](https://github.com/MrGiovanni/ContinualLearning/blob/main/requirements.txt) to the repository.

Thanks for your patience. Please let us know if you have any questions.

Best,
Zongwei
