### ISSUE TITLE
Question about "requirement.txt" and the pre-trained embedding file

### ISSUE THREAD

**Issue by mingsiliu557** [MrGiovanni/ContinualLearning#8]
Dear author, could you please tell us where can we get those files?

**Comment by MrGiovanni** [comment]
Hello @mingsiliu557 

I just uploaded [requirements.txt](https://github.com/MrGiovanni/ContinualLearning/blob/main/requirements.txt) and [pre-trained embedding](https://github.com/MrGiovanni/ContinualLearning/tree/main/pretrained_weights) to the repository.

Please let us know if you have any questions.

Best,
Zongwei

**Comment by mingsiliu557** [comment]
Thanks a lot. Wish you have more paper this year！

Zongwei Zhou ***@***.***>于2023年10月9日 周一23:27写道：
